[project]
name = "airlift"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.38.37",
    "datadog-api-client>=2.36.0",
    "pandas>=2.2.3",
    "splunk-sdk>=2.1.0",
]
